version: '3.3'

services:
  testdb:
    image: postgres:13.0-alpine
    volumes:
      - testdb_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - persist
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    ports:
      - 8002:80
    environment:
      PGADMIN_DEFAULT_EMAIL: codetest@utu.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - persist
volumes:
  testdb_data: {}
  pgadmin-data: {}
networks:
  persist: {}